# Generated by Django 2.2.4 on 2019-09-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mailing',
            field=models.BooleanField(blank=True, default=False, verbose_name='Рассылка на почту'),
        ),
    ]
