# Generated by Django 2.2.2 on 2019-06-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Отчество')),
                ('full_name', models.CharField(max_length=128, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('sex',
                 models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=6,
                                  verbose_name='Пол')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('id',),
            },
        ),
    ]
