# Generated by Django 2.2.2 on 2019-06-28 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('file_mime', models.CharField(max_length=64, verbose_name='Тип файла')),
                ('file_size', models.PositiveIntegerField(verbose_name='Размер файла')),
                ('file_name', models.CharField(max_length=32, verbose_name='Имя файла')),
            ],
            options={
                'verbose_name': 'Аватар',
                'verbose_name_plural': 'Аватары',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Avatar',
                                    verbose_name='Аватар'),
        ),
    ]
