# Generated by Django 2.2.2 on 2019-06-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rest_api', '0009_auto_20190629_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='content_type',
            field=models.CharField(max_length=16, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='file_name',
            field=models.CharField(max_length=1024, verbose_name='Имя файла'),
        ),
    ]
