# Generated by Django 2.2.2 on 2019-06-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rest_api', '0010_auto_20190629_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='file',
            field=models.ImageField(unique_for_date=True, upload_to='avatars', verbose_name='Файл'),
        ),
    ]
