# Generated by Django 2.2.4 on 2019-08-17 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rest_api', '0012_auto_20190629_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
    ]
