# Generated by Django 2.2.1 on 2019-05-12 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='attachments', verbose_name='Файл')),
                ('file_name', models.CharField(max_length=500, verbose_name='Имя файла')),
                ('file_mime', models.CharField(max_length=500, verbose_name='Расширение файла')),
                ('file_size', models.IntegerField(verbose_name='Размер файла')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='Полное название организации')),
                ('short_name', models.CharField(max_length=128, verbose_name='Сокращенное название организации')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('inn', models.CharField(max_length=16, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=16, verbose_name='КПП')),
                ('ogrn', models.CharField(max_length=32, verbose_name='ОГРН')),
                ('okved_code', models.CharField(max_length=32, verbose_name='Код ОКВЭД')),
                ('okved_name', models.CharField(max_length=512, verbose_name='Расшифровка ОКВЭД')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'unique_together': {('inn', 'kpp')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('sex',
                 models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=6,
                                  verbose_name='Пол')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='API.Attachment', verbose_name='Фотография')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='employees', to='API.Organization',
                                                   verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
