# Generated by Django 2.2.1 on 2019-05-20 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ('id',), 'verbose_name': 'Вложение', 'verbose_name_plural': 'Вложения'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('id',), 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('id',), 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
    ]
