# Generated by Django 2.2.1 on 2019-05-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20190510_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='full_name',
            field=models.CharField(max_length=128, verbose_name='Полное название организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(max_length=128, verbose_name='Сокращенное название организации'),
        ),
    ]
