# Generated by Django 2.2.1 on 2019-05-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('API', '0007_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='attachments', verbose_name='Фотография'),
        ),
    ]
