# Generated by Django 2.2.1 on 2019-05-10 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('API', '0009_auto_20190510_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='API.Attachment', verbose_name='Фотография'),
        ),
    ]
