# Generated by Django 2.2.1 on 2019-05-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('API', '0010_auto_20190510_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.ImageField(upload_to='attachments', verbose_name='Файл'),
        ),
    ]
