# Generated by Django 2.2.1 on 2019-05-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('API', '0011_auto_20190510_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=6,
                                   verbose_name='Пол'),
        ),
    ]
