# Generated by Django 3.0.4 on 2020-03-17 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('common_models_app', '0002_auto_20191203_2355'),
        ('tasks_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned',
                                    to='users_app.Profile', verbose_name='Кто назначил'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_taken',
                                    to='users_app.Profile', verbose_name='Кому назначено'),
        ),
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='task', to='common_models_app.Attachment',
                                       verbose_name='Вложение к заданию'),
        ),
    ]
