# Generated by Django 3.0.4 on 2020-03-19 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('common_models_app', '0002_auto_20191203_2355'),
        ('tasks_app', '0002_auto_20200317_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('id',), 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='common_models_app.Attachment', verbose_name='Вложение к заданию'),
        ),
    ]
