# Generated by Django 2.2.4 on 2019-09-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks_app', '0002_auto_20190921_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
