# Generated by Django 2.2.4 on 2019-09-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks_app', '0003_task_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_of_issue',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dead_line',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок исполнения'),
        ),
    ]
