# Generated by Django 2.2.7 on 2019-12-03 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks_app', '0005_task_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='task', to='common_models_app.Attachment',
                                       verbose_name='Вложение к заданию'),
        ),
    ]
