# Generated by Django 3.1.2 on 2020-10-20 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('common_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=128, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('date_of_issue', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('dead_line', models.DateTimeField(blank=True, null=True, verbose_name='Срок исполнения')),
                ('done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('assigned_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Кто назначил')),
                ('assigned_to',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_taken',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Кому назначено')),
                ('attachment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                    to='common_models.attachment', verbose_name='Вложение к заданию')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'db_table': 'tasks',
            },
        ),
    ]
