# Generated by Django 2.2.7 on 2019-12-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments', verbose_name='Файл')),
                ('file_name', models.CharField(max_length=64, verbose_name='Имя файла')),
                ('file_mime', models.CharField(max_length=16, verbose_name='Тип файла')),
                ('file_size', models.PositiveIntegerField(verbose_name='Размер файла')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
    ]
