# Generated by Django 2.2.7 on 2019-12-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('common_models_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_mime',
            field=models.CharField(max_length=128, verbose_name='Тип файла'),
        ),
    ]
