# Generated by Django 3.0.5 on 2020-05-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models_app', '0002_auto_20191203_2355'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachment',
            table='attachments',
        ),
    ]
